# Generated by Django 3.1 on 2020-08-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('A', 'active'), ('x', 'p0 won'), ('y', 'p1 won')], default='A', max_length=1),
        ),
    ]
